### ISSUE TITLE
RTNETLINK answers: Invalid argument / We have an error talking to the kernel

### ISSUE THREAD

**Issue by aguadopd** [magnific0/wondershaper#17] opened 2018-01-25 16:36 UTC
Related to #8? 
I'm on Linux asus 4.13.0-25-generic #29-Ubuntu SMP Mon Jan 8 21:14:41 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux.  
The package of the same name in Ubuntu is not working either, [bug filed here](https://bugs.launchpad.net/ubuntu/+source/wondershaper/+bug/1745421).

```
$ sudo ./wondershaper -a wlp3s0 -d 1024 -u 300
RTNETLINK answers: File exists
RTNETLINK answers: File exists
RTNETLINK answers: File exists
RTNETLINK answers: File exists
RTNETLINK answers: File exists
RTNETLINK answers: File exists
RTNETLINK answers: File exists
RTNETLINK answers: File exists
RTNETLINK answers: Invalid argument
We have an error talking to the kernel
RTNETLINK answers: Invalid argument
We have an error talking to the kernel
RTNETLINK answers: Invalid argument
We have an error talking to the kernel
RTNETLINK answers: Invalid argument
We have an error talking to the kernel
RTNETLINK answers: Invalid argument
We have an error talking to the kernel
RTNETLINK answers: File exists
RTNETLINK answers: File exists
RTNETLINK answers: File exists
```

**Comment by xBioClown** [comment] 2018-01-29 15:43
got the same issue, i have the offical version instaled with _sudo apt install wondershaper_, and used as root

**Comment by lefrankleal** [comment] 2018-01-29 15:47
same issue here, have the version instaled from the official repos.

**Comment by chamfay** [comment] 2018-02-14 22:38
I've the same issue using KDE neon lts
**uname -a** command output:
`Linux neon 4.13.0-32-generic #35~16.04.1-Ubuntu SMP Thu Jan 25 10:13:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by magnific0** [comment] 2018-02-16 10:11
@lefrankleal the version installed by apt is probably 1.1, while the one hosted here is 1.4. So that has been confirmed to not work. 

@aguadopd and @chamfay can you please post output of the following (example adapted for @aguadopd):

    sudo ./wondershaper -c -a wlp3s0
    sudo ./wondershaper -a wlp3s0 -d 1024

Limiting only the download.

**Comment by magnific0** [comment] 2018-02-16 10:56
I have just read up a bit and my guess is that:

    RTNETLINK answers: Invalid argument
We have an error talking to the kernel

commonly occurs after the kernel has been updated (updated using your package manager, but not loaded). It's best to reboot the system and see if this solves the issue.

    RTNETLINK answers: File exists

occurs you have previously set rules. It's only a warning, so shouldn't impact the operations. However, to get rid of this, do

    sudo ./wondershaper -c -a <interface>

to clear the rules.

**Comment by chamfay** [comment] 2018-02-16 12:55
Yes,
when i use package installed with apt, the problem still the same:
```
$ sudo wondershaper enp2s0 512 512
RTNETLINK answers: Invalid argument
We have an error talking to the kernel
RTNETLINK answers: Invalid argument
We have an error talking to the kernel
RTNETLINK answers: Invalid argument
We have an error talking to the kernel
RTNETLINK answers: Invalid argument
We have an error talking to the kernel
RTNETLINK answers: Invalid argument
We have an error talking to the kernel
```

but when i use git version there is no problem, the script working fine! but must run clear before
`sudo ./wondershaper -c -a enp2s0 && sudo ./wondershaper -a enp2s0 -d 512 -u 512`

**Comment by magnific0** [comment] 2018-02-16 13:06
@chamfay thanks for confirming so quickly.

The old version (shipped with distros) is broken with newer kernels and for sure won't work anymore. I'm closing this issue. Feel free to reopen @lefrankleal @aguadopd if the issue remains unsolved for you after updating to the latest version (1.4) from here.

**Closed by magnific0** 2018-02-16 13:06 UTC

**Comment by aguadopd** [comment] 2018-02-20 01:53
@magnific0 I can't recall if I had rebooted when that happened. But just tried and it works! Almost sure it was what you pointed out. Just in case, it seems that the kernel is now slightly updated.

```sh
$ uname -a
Linux asus 4.13.0-32-generic #35-Ubuntu SMP Thu Jan 25 09:13:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

Thanks a lot. This tool is very important for me when working in a shared network. Have a great week.

**Comment by lope** [comment] 2018-04-24 22:55
Ubuntu 16.04 4.13.0-39-generic
I had this issue also.
It was driving me nuts because the old wondershaper used to work on older kernels, and I thought maybe I was missing kernel modules or something.

The new wondershaper works if I run it like this
```
./wondershaper -c -a foo
./wondershaper -a foo -d 1000 -u 500
```

**Comment by mwoolweaver** [comment] 2019-11-29 15:32
Not why we have to clear the adapter settings and then reset them for wondershaper to work...

Fought this issue for about 6hrs for it to be the answer found in this issue...

**Comment by mwoolweaver** [comment] 2019-11-29 18:43
My solution was to make a script a make in run at reboot with a cron job.


Put the following 2 commands in a script 

`wondershaper -c -a foo`
`wondershaper -a foo -d 1000 -u 500`

Run 

`sudo crontab -e`

Once the editor is open add

`@reboot sudo /path/to/script`

**Comment by drahnr** [comment] 2020-03-27 07:36
The issue still persists within the shipped `wondershaper.service` file - a fixed version is here: https://github.com/drahnr/wondershaper-rpm

**Comment by simoschip2000** [comment] 2025-02-25 10:51
Issue still persists. Can't the new version be applied for apt?
